using System.IO;
using System.Text;

namespace SpecBuilder.CodeGen
{
    public partial class Document : ICodeDomWriteable
    {
        private readonly Namespace _namespace;

        public Document(Namespace @namespace)
        {
            _namespace = @namespace;
        }

        public void Write(string filename)
        {
            using (var writer = new StreamWriter(filename, false, Encoding.UTF8))
            {
                // Write byte order mark
                var preamble = Encoding.UTF8.GetPreamble();
                writer.BaseStream.Write(preamble, 0, preamble.Length);
                writer.BaseStream.Flush();
                Write(writer, 0);
            }
        }

        public string Write()
        {
            using (var memoryStream = new MemoryStream())
            using(var writer = new StreamWriter(memoryStream, Encoding.UTF8))
            {
                Write(writer, 0);
                return Encoding.UTF8.GetString(memoryStream.ToArray());
            }
        }

        public void Write(StreamWriter writer, int tabs)
        {
            var indent = NameFormatter.Indent(tabs);
            writer.WriteLine(indent + "//");
            writer.WriteLine(indent + "// This file is generated by a tool.");
            writer.WriteLine(indent + "//");
            writer.WriteLine(indent + "// ReSharper disable InconsistentNaming");
            writer.WriteLine();
            writer.WriteLine(indent + "using System;");
            writer.WriteLine(indent + "using System.Runtime.InteropServices;");
            writer.WriteLine();
            _namespace.Write(writer, tabs);
        }
    }
}
